import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'VolleyPlanner terms of service - the rules for using VolleyPlanner.',
  alternates: {
    canonical: 'https://volleyplanner.co.uk/terms',
  },
}

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-16">

      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-vp-muted hover:text-vp-text transition-colors duration-150 mb-10"
      >
        &larr; Back to home
      </Link>

      <h1 className="font-display font-bold uppercase text-4xl sm:text-5xl text-vp-text leading-[0.92] tracking-tight mb-4">
        Terms of Service
      </h1>
      <p className="text-vp-muted text-sm mb-12">Last updated: March 2025</p>

      <div className="prose prose-sm max-w-none space-y-10 text-vp-muted leading-relaxed">

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">1. Acceptance of terms</h2>
          <p>
            By creating an account or using VolleyPlanner (&quot;the Service&quot;), you agree to
            these terms. If you do not agree, do not use the Service.
          </p>
          <p className="mt-3">
            These terms are governed by the laws of England and Wales.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">2. The Service</h2>
          <p>
            VolleyPlanner is a web application that uses AI to generate volleyball training session
            plans. Plans are generated by an AI model and should be reviewed by the coach before
            use. We make no guarantee that any generated plan is suitable for your specific
            circumstances, player abilities, or safety requirements.
          </p>
          <p className="mt-3">
            You are responsible for the safety and wellbeing of all players during any session you
            run. AI-generated plans are a starting point, not a substitute for your own coaching
            judgement.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">3. Accounts</h2>
          <p>
            You must provide a valid email address to create an account. You are responsible for
            keeping your account secure. Do not share access to your account.
          </p>
          <p className="mt-3">
            We reserve the right to suspend or terminate accounts that violate these terms or are
            used in ways that harm the Service or other users.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">4. Free and Pro tiers</h2>
          <p>
            Free accounts may generate up to 3 session plans per calendar month. Pro accounts
            (£6/month) provide unlimited plans and additional features as described on the pricing
            page.
          </p>
          <p className="mt-3">
            We reserve the right to change pricing or features with reasonable notice. Where
            possible, we will honour existing subscriptions at the price you signed up at for the
            duration of that subscription period.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">5. Payments and refunds</h2>
          <p>
            Pro subscriptions are billed monthly through Stripe. You may cancel at any time. On
            cancellation, your Pro access continues until the end of the current billing period.
            We do not offer refunds for partial months, except where required by UK consumer law.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">6. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="mt-3 space-y-2 list-disc list-inside">
            <li>Use the Service for anything other than legitimate coaching purposes</li>
            <li>Attempt to circumvent usage limits</li>
            <li>Scrape, copy, or redistribute generated content at scale</li>
            <li>Use the Service in ways that harm or disrupt it for others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">7. Intellectual property</h2>
          <p>
            Session plans generated through your use of VolleyPlanner are yours to use for
            personal and coaching purposes. We do not claim ownership of plans you generate.
          </p>
          <p className="mt-3">
            The VolleyPlanner application, brand, and underlying code remain our intellectual
            property. You may not copy or redistribute the application.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">
            8. Limitation of liability
          </h2>
          <p>
            To the maximum extent permitted by law, VolleyPlanner is provided &quot;as is&quot;
            without warranty. We are not liable for any injuries, losses, or damages arising from
            the use of session plans generated by the Service.
          </p>
          <p className="mt-3">
            Our total liability to you in any circumstances will not exceed the amount you have
            paid us in the 12 months before the claim.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">9. Changes to these terms</h2>
          <p>
            We may update these terms from time to time. We will notify you by email of any
            material changes. Continued use of the Service after changes take effect constitutes
            acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-vp-text font-semibold text-base mb-3">10. Contact</h2>
          <p>
            For any questions about these terms, contact us at{' '}
            <a href="mailto:hello@volleyplanner.co.uk" className="text-orange hover:underline">
              hello@volleyplanner.co.uk
            </a>
            .
          </p>
        </section>

      </div>
    </div>
  )
}
